FROM python:3.9
WORKDIR /code
COPY ./fastapi/app /code/app
COPY ./fastapi/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
CMD ["fastapi", "run", "/code/app/main.py", "--port", "80"]
